### PR TITLE
Add generated open graph images

### LINKED ISSUE #553: Implement generated Open Graph Images
CC's Open Graph Image Generator has had enough styling improvements that it's ready for production!

https://cc-og-image.vercel.app/

We can use this to add custom OG images to all pages and blog posts. Here's an example tag and image for a standard page:

og-image (1)

```html
<meta property="og:image" content="https://cc-og-image.vercel.app/This%20is%20the%20page%20title.png?theme=light&md=1&fontFamily=roboto-condensed&fontSize=100px&images=https%3A%2F%2Fcc-vocabulary.netlify.app%2Flogos%2Fproducts%2Fopen_source.svg%23opensource" />
```

The `This%20is%20the%20page%20title` piece should be replaced dynamically with the page's actual title.

## Blog Posts

For blog posts, we can include the author's image! Here's an example:

og-image (2)

```html
<meta property="og:image" content="https://cc-og-image.vercel.app/CREATIVE%20COMMONS%20WORDPRESS%20PLUGIN%3A%20ATTRIBUTION%20FOR%20IMAGES.png?theme=light&md=1&fontFamily=roboto-condensed&fontSize=100px&images=https%3A%2F%2Fcc-vocabulary.netlify.app%2Flogos%2Fproducts%2Fopen_source.svg%23opensource&images=https%3A%2F%2Fsecure.gravatar.com%2Favatar%2Fbca19ddd1522cb12edde0520d3d77ded%3Fsize%3D200%26d%3Dmp" />
```

The key for showing the author here is adding a second `&images={gravatar_url}` property to the meta url. In this case, that url is: `https%3A%2F%2Fsecure.gravatar.com%2Favatar%2Fbca19ddd1522cb12edde0520d3d77ded%3Fsize%3D200%26d%3Dmp`.

This will significantly improve the quality of social shares from the Open Source site.

### PR DESCRIPTION
**Pull request by zackkrida**
## Fixes

Fixes #553 by @zackkrida 

## Description

Creates an `og_image` lektor macro for generating the open graph image. All pages show their title, with a fallback to the text 'Open Source at CC' if for some reason a page doesn't have a title.

Additionally, posts will show the gravatar of their author and the author name. There's not a great way to detect if a user has a gravatar or not, so unfortunately users without will show the default gravatar, as opposed to showing no image, which would be preferable in this case.

Please review the macro and see if there's any way to clean up it's logic. Python + Lektor + Jinja templates aren't my forte. For example, I would've preferred to use a dict for the query params and build the url with `urllib.urlencode`, but I couldn't manage to import it correctly.

## Examples

[Open Source Projects Page](https://opensource.creativecommons.org/contributing-code/projects/)
Open Source Projects

[Blog Landing Page](https://opensource.creativecommons.org/blog/entries/)
CC Open Source Blog

[Example Blog Post](https://opensource.creativecommons.org/blog/entries/cc-wp-base-theme-docs-intro/)
sm_

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by zackkrida** [comment]
(Also noting, the style of the og images can change and be improved over time, without needing any code changes here. So if there's any concerns about text styles, image placement, etc., consider making a separate issue on https://github.com/creativecommons/og-image-generator)

**Comment by zackkrida** [comment]
@Dhruvi16 and @dhruvkb, I finally have something I can tag you _both_ on! Please review when you can; thank you!

**Comment by zackkrida** [comment]
Pinging you both again (@Dhruvi16 and @dhruvkb), but with some extra testing notes:

> Run this PR locally, and visit a few pages. Check for the `<meta property="og:image">` tag and view the url in the browser. Please check blog posts as well as pages.

**Comment by dhruvkb** [comment]
Sorry @zackkrida, it's been a busy sprint at work. Will try to review as soon as I have a moment.

**Comment by zackkrida** [comment]
@dhruvkb you can take your time—this isn't urgent, just wanted to make sure it's on your radar at all. Thanks!

**Review by dhruvkb — APPROVED** [review]
Twitter seems to be able to handle the URL but neither Facebook nor LinkedIn managed to load it. I suspect it could be because of the HTML markup in the URL, so I would suggest base64 encoding the entire string in the URL and then decoding it in the image generator.

Approving since we majorly tweet about the posts and not use the other two networks as much.

**Samples:**

Screenshot 2020-11-29 at 12 00 12 AM
^ Twitter
Screenshot 2020-11-29 at 12 00 20 AM
^ Facebook
Screenshot 2020-11-29 at 12 00 34 AM
^ LinkedIn

**Comment by dhruvkb** [comment]
Just in case, you want to test them yourself, here are the dev tools:
- [Twitter](https://cards-dev.twitter.com/validator)
- [Facebook](https://developers.facebook.com/tools/debug/)
- [LinkedIn](https://www.linkedin.com/post-inspector/inspect/)

**Review by akmadian — APPROVED** [review]

**Comment by zackkrida** [comment]
@dhruvkb thanks for testing thoroughly. The facebook issue is [known](https://github.com/creativecommons/og-image-generator/blob/ba20ca7b1bf15d4e94ca8202eacf01360ccbd220/api/_lib/parser.ts#L8) but I'd like to prioritize fixing it. I created an issue here: https://github.com/creativecommons/og-image-generator/issues/18.

**Comment by dhruvkb** [comment]
@zackkrida feel free to merge it if you think we can update the code for the other platforms later.

**Pull request merged**
