### PR TITLE
Publish technical blog archives

### PR DESCRIPTION
**Pull request by kgodey**
**Description**

Adds a blog to Lektor containing old CC technical blog posts.

Old posts are currently located here and not deployed anywhere AFAIK: https://github.com/creativecommons/labs/tree/gh-pages/_posts

**Remaining work**
- [ ] Import remaining blog posts from the `labs` repo 
    - [ ] Convert HTML to Markdown where appropriate
    - [ ] Include images associated with posts, (images are in the top level `<year>` directories).
    - [ ] Include categories (will require a change to the blog post model)
    - [ ] Fix URLs to other posts (currently points to `techblog.creativecommons.org` which does not exist).
- [ ] Verify that pagination works and style it appropriately.
- [ ] Show categories in UI
- [ ] Link to blog from navigation (not sure which section is the best place yet)

**Future work**
This work will be done in future pull requests.
- Create author pages that show all of one author's posts.
- Create category pages that show posts associated with a category.

**Checklist**
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [ ] My commit messages follow [best practices](https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53).
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by makkoncept** [comment]
Hi @kgodey, Can I work on this.
I can start working on the first task (_Import remaining blog posts from the labs repo_).

**Comment by kgodey** [comment]
Sure, go ahead!

**Comment by makkoncept** [comment]
@kgodey , i have made a [python scipt](https://gist.github.com/makkoncept/45303a19fc8e8ee45d7f96555e7e9e76) that does the first subtask(`Convert HTML to Markdown where appropriate`). 

For the second subtask, I want to point out that:
- some images are not present, eg [screen1m.jpg](https://github.com/creativecommons/labs/blob/gh-pages/_posts/2007-06-27-its-coming-cc-openofficeorg-add-in.html#L25), [screen2m.jpg](https://github.com/creativecommons/labs/blob/gh-pages/_posts/2007-06-27-its-coming-cc-openofficeorg-add-in.html#L27)
- some images are not in the `<year>` directories, but in top-level `img` directory. eg [2386059670_9aa013cf66_m.jpg](https://github.com/creativecommons/labs/blob/gh-pages/_posts/2008-04-03-stand-up-meeting-2004-04-01.html#L22), [2385228781_b6962f4526_m.jpg](https://github.com/creativecommons/labs/blob/gh-pages/_posts/2008-04-03-stand-up-meeting-2004-04-01.html#L22)

I have found most of the images in top level `img` directory but there might be few exceptions. So I think this directory can be used instead of `year` directories in the script.
What do you think?

Also just to clarify, URLs like these `http://techblog.creativecommons.org/2007/05/13/more-xmp-toolkit-plugs` should be changed to `https://creativecommons.github.io/tech-blog-archives/more-xmp-toolkit-plugs`?

**Comment by kgodey** [comment]
@makkoncept 
If the images are not present, just have an empty image tag (to indicate that there once was an image. You can get them from wherever in the repo makes sense, I didn't realize there was an `img/` folder too. You should probably check in both places before assuming it doesn't exist.

Images should be moved into the same directory as the `contents.lr` file and set up as Lektor attachments (see [docs here](https://www.getlektor.com/docs/content/attachments/)]. See the [contributing-code](https://github.com/creativecommons/creativecommons.github.io-source/tree/master/content/contributing-code) page for an example, it links to two images that are in the same folder.

**Comment by makkoncept** [comment]
@kgodey, will the default syntax of markdown for the image( `img` ) not work? The script is able to parse the img tag, and convert it to this syntax.

Also just to clarify, URLs like these `http://techblog.creativecommons.org/2007/05/13/more-xmp-toolkit-plugs` should be changed to `https://creativecommons.github.io/tech-blog-archives/more-xmp-toolkit-plugs?`

**Comment by kgodey** [comment]
@makkoncept I'm not sure which folder the images are served from, you can try it and see if it works. I think it's better to do it in a way that's idiomatic in Lektor.

**Comment by makkoncept** [comment]
@kgodey Can you please tell me how to include categories?
Do we have to do something like this?
```
title: wiki.creativecommons.org skin available
---
categories: mediawiki, releases, software
---
author: nathan
---
body:

```

**Comment by kgodey** [comment]
You have to add a field to the blog post model (see `/models/blog-post.ini`) For now, just add the categories as a single comma separated field, I'll make a separate ticket for actually implementing category pages (the Lektor guide is here, for reference: https://www.getlektor.com/docs/guides/categories/)

**Comment by makkoncept** [comment]
@kgodey  I have updated the [script](https://gist.github.com/makkoncept/45303a19fc8e8ee45d7f96555e7e9e76). 
Can you test it locally?
 Put it in root with `_posts` and `img` directories. It needs _bs4_ and _html2text_ packages

**Comment by kgodey** [comment]
@makkoncept tested and looks good 👍. However the most recent post is on 2012-07-11 and I know there are blog posts up to 2014 in the original repo. Could you make sure all blog posts and images are ported over (maybe count them pre-transformation and post-transformation independently and make sure they match)?

**Comment by makkoncept** [comment]
ok @kgodey. Do I make a separate pull request with the all the changes?

**Comment by kgodey** [comment]
yes, please do.

**Comment by kgodey** [comment]
I'm going to merge this in to prepare for @makkoncept's PR.

**Pull request merged**
