### PR TITLE
Fixed relative path to all projects page

### LINKED ISSUE #303: Relative path error with page links when in development
## Description

Relative path error when in development. 
My branch is up to date with `creativecommons.github.io-source master`. There isn't such an issue on the live site, hence the mention of _development_.

## Reproduction

1. Go to the index page
2. Try clicking `All our projects` in the `Integrate with CC Tools` card.
3. Notice the URL on your browser if a 404

## Expectation

Relative path should work correctly as intended.

## Screenshots

Screenshot from 2020-06-16 14-56-42
Screenshot from 2020-06-16 14-56-46

## Environment

 - Device: laptop
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 83.0.4103.61 (Official Build) (64-bit)
 - Other info: 1366x768 (16:9)

## Resolution

- [ ] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by ritesh-pandey**
## Fixes

Fixes #303 by @sp35 

## Description

Fixes relative path to `all projects` page from homepage.

## Tests

Click on `all projects` link. It should take you to correct page.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by ritesh-pandey** [comment]
Got it. Thanks for pointing that out.
```
curl -I http://localhost:5000/contributing-code/projects
HTTP/1.0 301 MOVED PERMANENTLY
Content-Type: text/html; charset=utf-8
Content-Length: 261
Location: http://localhost:5000/contributing-code/contributing-code/projects/
Server: Werkzeug/0.16.1 Python/3.7.8
Date: Mon, 13 Jul 2020 15:37:29 GMT
```
vs 

```
curl -I http://localhost:5000/contributing-code/projects/
HTTP/1.0 200 OK
Cache-Control: no-cache, no-store
Content-Type: text/html; charset=utf-8
Server: Werkzeug/0.16.1 Python/3.7.8
Date: Mon, 13 Jul 2020 15:37:44 GMT
```
I think a missing trailing slash is creating problem. Instead of pointing to `projects` file, we should point to `projects/` directory. This way the system won't redirect the request.

**Comment by sp35** [comment]
Thanks @ritesh-pandey. I'm convinced 😊.
Can you check for other such links?

**Comment by ritesh-pandey** [comment]
I have checked and fixed the occurences in `content/contents.lr` file.

**Comment by kgodey** [comment]
@ritesh-pandey this looks good but there are lots of these errors all over the site. I'll merge this, but it would be great to get the others fixed as well.

**Comment by kgodey** [comment]
Thanks for figuring out the issue!

**Comment by ritesh-pandey** [comment]
@kgodey  Is it safe to assume that all such errors are relative URLs? 

I `grep` ed `content` folder for relative URLs.

```
ritesh@ritesh-Inspiron-5548:~/github/ritesh-pandey/creativecommons.github.io-source$ grep -inr "href=[\'\"][/]" content/
content/community/write-a-blog-post/contents.lr:9:<p class="lead">We invite members of the Creative Commons community to write guest posts on <a href="/blog">our technical blog</a>.</p>
content/community/contents.lr:9:<p class="lead">Join our Slack or mailing list communities to meet other developers interested in Creative Commons, get feedback on your projects, and talk with CC's full-time engineering staff. You can also keep up with us on the <a href="/blog">CC Open Source Blog</a> or via <a href="https://twitter.com/cc_opensource">Twitter</a>.</p>
content/contents.lr:21:      <a href="/community/" class="btn btn-sm btn-outline-primary">See how to join</a>
content/contents.lr:32:      <a href="/contributing-code/" class="btn btn-sm btn-outline-primary">Guidelines</a>
content/contents.lr:45:      <a href="/contributing-code/projects/" class="btn btn-sm btn-outline-primary">All our projects</a>
content/contents.lr:55:      <p class="card-text text-center">If you've worked on software that uses CC licenses or tools, tell the community about it on <a href="/blog/">our tech blog</a>.</p>
content/contents.lr:56:      <a href="/community/write-a-blog-post/" class="btn btn-sm btn-outline-primary">Write a blog post</a>
content/contents.lr:67:      <a href="/contributing-code/usability/" class="btn btn-sm btn-outline-primary">Learn more</a>
```

Looks like there are two more occurrences which we need to fix.
- content/community/write-a-blog-post/contents.lr:9
- content/community/contents.lr:9

**Comment by kgodey** [comment]
@ritesh-pandey yes, I think that's safe assumption.

**Pull request merged**
