### PR TITLE
added description content for meta description

### LINKED ISSUE #184: description content for optimised social sharing
## Problem Description

Add the description content to be shown while sharing the link on Facebook and Twitter.
image-preview

From the above image, you can see the **description part** is missing. Only the title and image are shown.

## Solution Description
I have already added the [image preview feature](https://github.com/creativecommons/creativecommons.github.io-source/pull/183) the only thing that is lacking is the description part that will be shown when any link will be shared.

## Helping Hands
You can get the content part of a page/post and then first strip HTML tags to convert into plain text and then get the first 20 words or so to be used in the description part.
Some plugins that you can play with [strip-html-tags](https://www.getlektor.com/plugins/lektor-strip-html-tags/) and [markdown-excerpt](https://www.getlektor.com/plugins/lektor-markdown-excerpt/)

## Note
Please don't add new fields, use the one that are already implemented, read more about it [here](https://github.com/creativecommons/creativecommons.github.io-source/pull/127#pullrequestreview-304886607)

### PR DESCRIPTION
**Pull request by techievivek**
## Fixes
Fixes #184 by @techievivek 

## Description
Added description content for meta tags for better social share.

## Technical details
Added [markdown-excerpt](https://www.getlektor.com/plugins/lektor-markdown-excerpt/) Lektor plugin to achieve this. Also in some page **body** part was missing so I extracted content from **description** part.

## Tests
View the source code of any page and try to see `meta description tag`
## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
@techievivek Please post screenshots of various pages being shared.

**Comment by techievivek** [comment]
@kgodey I have added the screenshot for various pages in the screenshot section of PR, there is one thing that is still not covered. In some of the pages, there is no **body or description part** like a specific category page, author page. One field that can be used is **name** field, so the pages which do not have **body or description part**, can we use **name**?

**Comment by techievivek** [comment]
@kgodey I have also updated my PR to first try **description** and then **body**.

**Comment by techievivek** [comment]
breno
@kgodey, For example, the author page does not have body or description field.

**Comment by techievivek** [comment]
@kgodey This is how it looks for author pages(page with no body, description part).
Screenshot_20200402-230442__01
Without adding name field too it works.

**Comment by kgodey** [comment]
Thanks @techievivek!

**Pull request merged**
