### PR TITLE
Used colored label component in /contributing-code page

### LINKED ISSUE #507: Use new colored label component in `/contributing-code` page
## Problem

Once #502 lands, we should use the new `.gh-label` css classes on [this page](https://github.com/creativecommons/creativecommons.github.io-source/blob/master/content/contributing-code/contents.lr), instead of inline code blocks.

## Implementation

- [ ] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by ooyeraju**
## Fixes

Fixes #507  by @zackkrida 

## Description
Used colored label components in /contributing-code page as mentioned in the issue

## Screenshots

Screenshot from 2020-09-29 23-46-55

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — CHANGES_REQUESTED** [review]
These are good! Please also make the changes in lines 40-43 as they also mention these labels.

**Review by dhruvkb — APPROVED** [review]

**Comment by zackkrida** [comment]
Noting that the https://opensource.creativecommons.org/contributing-code#proposing-a-new-issue seems to have been missed. We need to update the `not ready for work` label too.

**Comment by ooyeraju** [comment]
I didn't find any label for *not ready for work *

**Comment by zackkrida** [comment]
@ooyeraju Yup, there isn't one anymore. I'll make a separate ticket to re-name that issue and update it. Thanks again for your PR!

**Comment by ooyeraju** [comment]
If you want I can work on this.

**Pull request merged**
