### PR TITLE
added desciption in meta tag

### LINKED ISSUE #184: description content for optimised social sharing
## Problem Description

Add the description content to be shown while sharing the link on Facebook and Twitter.
image-preview

From the above image, you can see the **description part** is missing. Only the title and image are shown.

## Solution Description
I have already added the [image preview feature](https://github.com/creativecommons/creativecommons.github.io-source/pull/183) the only thing that is lacking is the description part that will be shown when any link will be shared.

## Helping Hands
You can get the content part of a page/post and then first strip HTML tags to convert into plain text and then get the first 20 words or so to be used in the description part.
Some plugins that you can play with [strip-html-tags](https://www.getlektor.com/plugins/lektor-strip-html-tags/) and [markdown-excerpt](https://www.getlektor.com/plugins/lektor-markdown-excerpt/)

## Note
Please don't add new fields, use the one that are already implemented, read more about it [here](https://github.com/creativecommons/creativecommons.github.io-source/pull/127#pullrequestreview-304886607)

### PR DESCRIPTION
**Pull request by nik-gautam**
Fixes #184 

## Description
Added description in the meta tag for SEO & better social media sharing. This provides a description of the webpage while sharing at social media platforms.    

## Other information
I have also added another Lektor plugin called `lektor-strip-html-tags`, set at version 0.3.1.

## Checklist
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin
```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

### CODE REVIEW

**Comment by nik-gautam** [comment]
@kgodey i will add the screenshot by tomorrow, ma'am. I had some trouble while deploying for testing.

**Comment by techievivek** [comment]
> @kgodey i will add the screenshot by tomorrow, ma'am. I had some trouble while deploying for testing.

Use [ngrok](https://ngrok.com/download) or some other tool to expose your localhost and then you can share the URL on different social media website for testing.

**Comment by nik-gautam** [comment]
Screenshot_2020-03-12-12-11-52-017_com whatsapp


Thanks for the advise @techievivek ..

**Comment by nik-gautam** [comment]
@kgodey Pages like [this](https://opensource.creativecommons.org/internships/) which don't have a description at the starting of the page don't work properly with the current implementation and produce nonsensical output.

Screenshot:-
Screenshot_2020-03-12-12-22-49-370_com whatsapp

**Comment by techievivek** [comment]
@kgodey @nik-gautam rather than splitting using dot(.) we can split using </p> and then get maybe the first item from the list.
This might work.🤔

**Comment by nik-gautam** [comment]
@kgodey @techievivek using `<p>` might work. I will test and report the results by tomorrow morning.

Thanks

**Comment by nik-gautam** [comment]
I am having this error while splitting by `<p>`

`<meta property="og:description" content="&lt;p class=&#34;lead&#34;&gt;Join our Slack, IRC, or mailing list communities to meet other developers interested in Creative Commons, get feedback on your projects, and talk with CC&#39;s full-time engineering staff. You can also keep up with us on the &lt;a href=&#34;/blog&#34;&gt;CC Open Source Blog&lt;/a&gt; or via &lt;a href=&#34;https://twitter.com/cc_opensource&#34;&gt;Twitter&lt;/a&gt;.&lt;/p&gt;&lt;h2 id=&#34;mailing-lists&#34;&gt;Mailing Lists&lt;/h2&gt;" />`
 
The only solution, which I could think of, is to removing the unwanted string is using regex.

**Comment by nik-gautam** [comment]
@kgodey @techievivek  I tried using this 
`set body = ((this.body|string).split("<p>")[0])|striphtmltags`

but the error here is not all pages have the first p tag as description.

Like `/community/` works fine with output:
`<meta property="og:description" content="Join our Slack, IRC, or mailing list communities to meet other developers interested in Creative Commons, get feedback on your projects, and talk with CC&#39;s full-time engineering staff. You can also keep up with us on the CC Open Source Blog or via Twitter.Mailing Lists" />` 
 
but for `/`:
`<meta property="og:description" content="" />` 
i.e no output 
but it works for `set body = ((this.body|string).split("<p>")[1])|striphtmltags`

**Comment by techievivek** [comment]
Try with closing p tag (`</p>`) rather than opening p tag.

**Comment by nik-gautam** [comment]
Nope, that won't work either. As that also include the previous `<h1>`& other tags before the first `</p>` tag.

**Comment by techievivek** [comment]
One thing you can try is once you have split based on closing p tag, now split the first time in the list on basis of closing h1 tag and then get the last item from the list, certainly that will be the content of the p tag.
You can try playing with it or else you will have to create a custom template tag to achieve all this.

**Comment by nik-gautam** [comment]
I was hoping to use some regex. But sure, I will give this a shot too.

**Comment by nik-gautam** [comment]
Sorry, my bad

**Comment by kgodey** [comment]
@nik-gautam what is the status of this PR?

**Comment by nik-gautam** [comment]
Sorry, I got really distracted with the current state, because I am stuck at hostel due to the lockdown in my country

**Comment by kgodey** [comment]
@nik-gautam We need it to work for all pages before I can merge it. I understand that you may not have time to work on it, please let me know if you'll be unable to complete it.

**Comment by techievivek** [comment]
@kgodey I tried using the plugin [markdown-excerpt](https://www.getlektor.com/plugins/lektor-markdown-excerpt/), which renders the first paragraph of Markdown, and its working. Previously I tried using the same but due to some issue I was unable to install and use it. But I tried it again today morning and it worked after some try.
Also in some of the pages, **body** part was not there so I used **description** to extract content.
(I just have a doubt whether we should give priority to description or body, from my view description can be given priority as it actually represents what the page is all about, so I will have to update my PR).
Otherwise, everything is working fine.
Please have a look at PR #212

**Comment by kgodey** [comment]
@techievivek I agree that description should have priority, please update your PR. And thank you!

**Comment by techievivek** [comment]
@kgodey I will soon update my PR and add screenshot for some of the pages.

**Comment by kgodey** [comment]
@nik-gautam thank you for your work on this, it really helped us get to the right solution. I'm going to close this PR because the issue was fixed in https://github.com/creativecommons/creativecommons.github.io-source/pull/212.

**Pull request closed without merging**
