### PR TITLE
Ordering roles

### LINKED ISSUE #481: Ordering of Roles under some projects
## Description
On the [Community Team page](https://opensource.creativecommons.org/community/community-team/members/), the ordering of the roles under **CC Catalog API** and **Community Building Teams** seems to be in reverse order than all others (This is only the case with these two categories).
It looks a little inconsistent with the other Projects ordered differently.

## Reproduction

Visit the  [Community Team page](https://opensource.creativecommons.org/community/community-team/members/).

## Expectation

The order should be reversed to have decreasing priority of roles.

## Screenshots

Screenshot from 2020-08-26 06-35-14

## Resolution

- [ ] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by ooyeraju**
## Fixes

Fixes #481  by @akshgpt7

## Description
Ordered roles under the cccatalog-api in Community Team Members page.

## Screenshots

Screenshot from 2020-08-27 12-51-59

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by Dhruvi16** [comment]
> @ooyeraju that data is automatically generated and will get overwritten, so this fix will not work.
> 
> You'll need to fix it in the template: https://github.com/creativecommons/creativecommons.github.io-source/blob/master/themes/vocabulary_theme/templates/community_team_list.html or where the data is generated: https://github.com/creativecommons/ccos-scripts/tree/master/push_data_to_ccos

This will be fixed where the data is generated and not the template.

**Comment by ooyeraju** [comment]
All other names are coming in an ordered way as both the scripts are general. So what I need to do in order to change the names in cccatalog-api ?

**Comment by kgodey** [comment]
@ooyeraju you'll need to edit this function in the `ccos-scripts` repo: https://github.com/creativecommons/ccos-scripts/blob/master/push_data_to_ccos/get_community_team_data.py#L19

**Review by dhruvkb — CHANGES_REQUESTED** [review]
~This file is autogenerated by a script in `creativecommons/ccos-scripts`. Any changes made to it will be overwritten when the script runs again.~

Nothing I said hasn't been said already.

**Comment by ooyeraju** [comment]
Should I close this PR? As the issue is solved in this https://github.com/creativecommons/ccos-scripts/issues/70

**Comment by kgodey** [comment]
Closed, thanks for your work on this!

**Pull request closed without merging**
