### PR TITLE
GitHub Repository Icon on Top Left corner 

### LINKED ISSUE #191: Github repo link on top left corner is not clickable on mobile devices.
## Describe the bug
GitHub repository link for CC opensource website is not clickable on mobile devices and thus donot redirect to CC opensource website GitHub repo. And also the design can be changed a bit as it is almost unrecognisable as GitHub logo.

## To Reproduce
1. Open the site in mobile.
2. Try clicking on the top left corner (github icon).
3. It doesn't responds to click.

## Expected behavior
It must redirect to CC opensource website repository.

## Screenshots
Screenshot_20200302-205145

## Smartphone (please complete the following information)
 - Device: One plus 7T
 - OS: Android 10
 - Browser: Chrome
 - Version (ex. 22)

## Additional context
Design for small devices can be changed a bit as it is almost unrecognisable as GitHub logo.

### PR DESCRIPTION
**Pull request by harsh551**
Fixes #191 

## Description

Changes made to templates/layout.html
It's Now Working, Here is attached image
a
## Line 31-32 is moved to Line 110-111
              `<a href="https://github.com/creativecommons/creativecommons.github.io-source" target="_blank" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; left: 0; transform: scale(-1, 1);" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg> </a>`
I have moved line 31-32 to line 110-111 ( templates/layout.html file )
## Checklist
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin
```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

### CODE REVIEW

**Comment by harsh551** [comment]
Ok mam

**Comment by harsh551** [comment]
Hey, mam @kgodey, I have made changes to commit message and PR is also edited to easily understand where I made changes in code. If there are any other changes requested, please let me know.

**Comment by kgodey** [comment]
assigning to @hugosolar to review.

**Comment by harsh551** [comment]
😀

**Comment by hugosolar** [comment]
Hey @harsh551 could you please make a new PR with better commit messages?

we think "Commited" does not follow the Commit messages [Best practices](https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53)

let me know if you have any comments or concerns

**Comment by harsh551** [comment]
Ok @hugosolar

**Pull request closed without merging**
