### PR TITLE
feat: Responsiveness bug

### LINKED ISSUE #490: Responsiveness Design Bug
## Description
The [Write a Blog Post](https://opensource.creativecommons.org/community/write-a-blog-post/) page under the community tab isn't responsive and a lot of content is getting clipped.

## Screenshots
I have adjusted the viewport to `1295px`. Please notice that the `Archives` tab on the navbar isn't visible.

image

Similarly, the content of the post isn't visible for some widths. You can refer to this [link](https://youtu.be/jSqC_tOMshY) for a live demo.

Additionally, for screens with viewport `<769px` I think everything is just perfect.

## Reproduction
Please remove the `overflow-x: hidden;` property on the `body` element just to visualize the clipped content. You will be able to notice a very long horizontal scrollbar. 

## Environment
 - Device: Laptop
 - OS: Windows10
 - Browser: Chrome and Firefox

## Resolution

- [ ] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by khushishikhu**
## Fixes 

Fixes #490 by @subhamX 

## Description
website is responsive now as shown in the screenshot

## Screenshots

Capture
Capture2

## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — CHANGES_REQUESTED** [review]
Setting `margin-left` to an arbitrary value is not a recommended solution.

**Comment by khushishikhu** [comment]
@dhruvkb can you please explain me further more for what kind of solution is required for the issue to be fixed

**Comment by dhruvkb** [comment]
I'll have to check and get back to you but, in the meantime, I'll tag in @Dhruvi16 as she might be able to help faster.

**Comment by Dhruvi16** [comment]
Hey! @khushishikhu. A very simple solution to this would be to add the `is-three-quarters` class to the body div. You can see `is-one-quarter` added to the navigation part. Lemme know if you have any doubts 😄

**Comment by khushishikhu** [comment]
i did the required changes. please have a look now
Capture
Capture2

**Review by dhruvkb — APPROVED** [review]

**Comment by khushishikhu** [comment]
@dhruvkb can you please put here hacktoberfest-accepted as i am just left with one pr to complete that challenge

**Comment by dhruvkb** [comment]
@khushishikhu approving and merging the PR should qualify it for Hacktoberfest as per the guidelines:
Screenshot 2020-10-30 at 3 05 58 PM

**Comment by khushishikhu** [comment]
@dhruvkb okay , thank you 😊

**Pull request merged**
