### PR TITLE
created my first blog

### PR DESCRIPTION
**Pull request by PreciousOritsedere**
## Description

- Add blog post: How I Landed my First Internship with Outreachy

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by possumbilities** [comment]
@PreciousOritsedere Hi! Thanks for this!
Could you fill out the details on the PR to match with the one here loosely what's here: 
* #688 

It would be nice to have the screenshot, but its ok if that's not included.

**Comment by PreciousOritsedere** [comment]
> @PreciousOritsedere Hi! Thanks for this! Could you fill out the details on the PR to match with the one here loosely what's here:
> 
> * [add blog post: Thinking More Openly About Working In The Open #688](https://github.com/creativecommons/creativecommons.github.io-source/pull/688)
> 
> It would be nice to have the screenshot, but its ok if that's not included.

Thanks for pointing that out. I have updated it.

**Comment by possumbilities** [comment]
@PreciousOritsedere Hi! Thanks for this. Can you update the base branch so its current and I believe this repo includes files in the `.history` directory which shouldn't be included, so I would recommend you remove them.

**Comment by PreciousOritsedere** [comment]
> @PreciousOritsedere Hi! Thanks for this. Can you update the base branch so its current and I believe this repo includes files in the `.history` directory which shouldn't be included, so I would recommend you remove them.
> 
> Edit: Upon a second look I don't think you need to include the `Pipfile` either, so it should be removed too.

Okay
Could you please guide me on how to remove these? and how do you mean update the bas branch, I don't really get that part

**Comment by possumbilities** [comment]
Hi! @PreciousOritsedere to get the your local base branch current you'd need to go to your local repo, and make sure you are in the branch `blog-post`. You'd need to also make sure that this repository(the one you forked from) is listed as a remote in your repo and if not, then I'd suggest you add it. You can follow these instructions to add it as `upstream`: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-repository-for-a-fork

From there you'd do a `git fetch upstream` and then `git merge upstream/main`. That would make your local branch current with the upstream main branch here. 

Now that they're current you could make the other changes in the branch. You'd remove the .history directory from being tracked with `git rm .history`, and then you can commit that change.

And next you can do `git rm Pipfile` to remove it from tracking, and then you can commit that change.

Afterwards you should be able to do a push up to your repository fork with `git push origin blog-post` and then the PR here should automatically updated correctly to show that the branch is current and that the appropriate files are no longer included in it.

**Comment by PreciousOritsedere** [comment]
> Hi! @PreciousOritsedere to get the your local base branch current you'd need to go to your local repo, and make sure you are in the branch `blog-post`. You'd need to also make sure that this repository(the one you forked from) is listed as a remote in your repo and if not, then I'd suggest you add it. You can follow these instructions to add it as `upstream`: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-repository-for-a-fork
> 
> From there you'd do a `git fetch upstream` and then `git merge upstream/main`. That would make your local branch current with the upstream main branch here.
> 
> Now that they're current you could make the other changes in the branch. You'd remove the .history directory from being tracked with `git rm .history`, and then you can commit that change.
> 
> And next you can do `git rm Pipfile` to remove it from tracking, and then you can commit that change.
> 
> Afterwards you should be able to do a push up to your repository fork with `git push origin blog-post` and then the PR here should automatically updated correctly to show that the branch is current and that the appropriate files are no longer included in it.

Okay.. I'll do this now

**Review by possumbilities — APPROVED** [review]

**Pull request merged**
