### PR TITLE
Write a Blog post responsive design bug fixed

### LINKED ISSUE #490: Responsiveness Design Bug
## Description
The [Write a Blog Post](https://opensource.creativecommons.org/community/write-a-blog-post/) page under the community tab isn't responsive and a lot of content is getting clipped.

## Screenshots
I have adjusted the viewport to `1295px`. Please notice that the `Archives` tab on the navbar isn't visible.

image

Similarly, the content of the post isn't visible for some widths. You can refer to this [link](https://youtu.be/jSqC_tOMshY) for a live demo.

Additionally, for screens with viewport `<769px` I think everything is just perfect.

## Reproduction
Please remove the `overflow-x: hidden;` property on the `body` element just to visualize the clipped content. You will be able to notice a very long horizontal scrollbar. 

## Environment
 - Device: Laptop
 - OS: Windows10
 - Browser: Chrome and Firefox

## Resolution

- [ ] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by Yashs911**
## Fixes

Fixes #490  by @subhamX 

## Description
The content was getting clipped so I used a width:75%;

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — CHANGES_REQUESTED** [review]
Setting `width` to an arbitrary value is not a recommended solution.

**Comment by Yashs911** [comment]
@dhruvkb left container has width: 25%; so according to me right container width should be 75%.

width

**Comment by Yashs911** [comment]
@dhruvkb I think I found the problem
error3
due to this the container is moving outside body.

**Comment by dhruvkb** [comment]
Okay @Yashs911 then you should limit the width of the extra wide container.

**Comment by Yashs911** [comment]
@dhruvkb I tried changing the width but if I use 75% the rest 25% becomes margin. If you guide me how can I reduce the width of <pre> container.

**Comment by dhruvkb** [comment]
@Yashs911 if you take a look at the DOM [here](https://github.com/creativecommons/creativecommons.github.io-source/blob/a78fa59bcf98e74123355c2431b75e10e6dbca8f/themes/vocabulary_theme/templates/page-with-toc.html), you have two columns
```html
<div class="container">
  <div class="column is-one-quarter">...</div>
  <div class="column content">...</div>
</div>
```

The second column grows indefinitely because it does not have a fixed-width, which you rightly figured out! But instead of adding some CSS, a simpler solution is just to do this [here](https://github.com/creativecommons/creativecommons.github.io-source/blob/a78fa59bcf98e74123355c2431b75e10e6dbca8f/themes/vocabulary_theme/templates/page-with-toc.html#L116):
```html
<div class="container">
  <div class="column is-one-quarter">...</div>
  <div class="column is-three-quarters content">...</div>
</div>
```

**Review by dhruvkb — APPROVED** [review]

**Pull request merged**
