### PR TITLE
Update guidelines page.

### PR DESCRIPTION
**Pull request by Dhruvi16**
## Description

This PR updates the guidelines template.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by Dhruvi16** [comment]
I have two doubts here -
1. The content class is not working for the markdown - https://github.com/jgthms/bulma/issues/1603
2. I am not able to extract the ID from URL for the `table of contents` component.

**Comment by hugosolar** [comment]
> I have a doubt here -
> 
>     1. The content class is not working for the markdown - [jgthms/bulma#1603](https://github.com/jgthms/bulma/issues/1603)

Maybe you can extend bulma title clases inside the content class... does that make sense to you?

**Comment by Dhruvi16** [comment]
> > I have a doubt here -
> > ```
> > 1. The content class is not working for the markdown - [jgthms/bulma#1603](https://github.com/jgthms/bulma/issues/1603)
> > ```
> 
> Maybe you can extend bulma title clases inside the content class... does that make sense to you?

Ah! I am confused, I did not get you. I will explain my doubt for clearance - I wanted to use [content](https://bulma.io/documentation/elements/content/) class instead of `markdown` but when I use it, it does not apply to the markdown content.

**Comment by Dhruvi16** [comment]
> It looks great but same issue with the title on phone screens...
> maybe add `word-wrap: break-word` or reduce title size to avoid text overflow
> 
> Screen Shot 2020-07-06 at 4 02 53 PM

Alright will do it.

**Comment by Dhruvi16** [comment]
image
It looks like this when I use - `word-wrap: break-word;`

**Comment by hugosolar** [comment]
> > > I have a doubt here -
> > > ```
> > > 1. The content class is not working for the markdown - [jgthms/bulma#1603](https://github.com/jgthms/bulma/issues/1603)
> > > ```
> > 
> > 
> > Maybe you can extend bulma title clases inside the content class... does that make sense to you?
> 
> Ah! I am confused, I did not get you. I will explain my doubt for clearance - I wanted to use [content](https://bulma.io/documentation/elements/content/) class instead of `markdown` but when I use it, it does not apply to the markdown content.

Got it
I think the problem is because `node_modules/bulma/scss/elements/content.sass` is not included on Vocabulary
you may want to include that on vocabulary before use the `.content` class

**Comment by Dhruvi16** [comment]
> > > > I have a doubt here -
> > > > ```
> > > > 1. The content class is not working for the markdown - [jgthms/bulma#1603](https://github.com/jgthms/bulma/issues/1603)
> > > > ```
> > > 
> > > 
> > > Maybe you can extend bulma title clases inside the content class... does that make sense to you?
> > 
> > 
> > Ah! I am confused, I did not get you. I will explain my doubt for clearance - I wanted to use [content](https://bulma.io/documentation/elements/content/) class instead of `markdown` but when I use it, it does not apply to the markdown content.
> 
> Got it
> I think the problem is because `node_modules/bulma/scss/elements/content.sass` is not included on Vocabulary
> you may want to include that on vocabulary before use the `.content` class

Oh I did not check that my bad. Thanks for the solution.

**Comment by hugosolar** [comment]
> image
> It looks like this when I use - `word-wrap: break-word;`

yes... it looks better IMO haha
Otherwise you can try [hyphens](https://caniuse.com/#feat=css-hyphens)

**Comment by Dhruvi16** [comment]
This is ready for merge I guess.

**Pull request merged**
