### PR TITLE
move continuous deployement to github actions for CC opensource website

### LINKED ISSUE #48: Move continuous deployment to GitHub Actions
**Is your feature request related to a problem? Please describe.**
We currently use TravisCI. We'd like to use GitHub Actions instead.

**Describe the solution you'd like**
The project should build on GitHub Actions and the automatic build and deployment should work.

### PR DESCRIPTION
**Pull request by techievivek**
Fixes #48 

## Description
Added workflow file to move continuous deployment to github actions.

## Checklist
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin
```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

### CODE REVIEW

**Comment by techievivek** [comment]
@kgodey Please have a look and also the workflow filename.

**Comment by kgodey** [comment]
Looks good, I'll merge and see if it works.

**Comment by techievivek** [comment]
Is it working? I can see it completed one task in the Actions tab.

**Comment by kgodey** [comment]
It's mostly working but the git push to the other repo failed, I'm fixing. I had to set a username and password in the repo settings.

**Comment by techievivek** [comment]
Ok, Please let me know once it is ready.
Thank you.

**Comment by kgodey** [comment]
I made a draft PR here: https://github.com/creativecommons/creativecommons.github.io-source/pull/204, I'll convert to a full PR when ready.

**Comment by kgodey** [comment]
That PR is merged, I also had to make a small PR https://github.com/creativecommons/creativecommons.github.io-source/pull/205 to fix the ref to master. It's all working now.

**Comment by techievivek** [comment]
> That PR is merged, I also had to make a small PR #205 to fix the ref to master. It's all working now.

Great :tada:

**Pull request merged**
